title: Stuart Woodward's Homepage

# Author settings
author:
  name: Stuart Woodward 
  email: stuart at stuartwoodward dot com 

# Markdown settings
markdown: kramdown
#highlighter: none
kramdown:
  input: GFM

# Exclude files or directories from the build
exclude:
  - README.md

# Plugins (add if you are using Jekyll plugins)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

description: |
  This is Stuart Woodward's browser homepage which is opened whenever he opens a new browser tab. It is configured in the browser to do so.

