theme: jekyll-theme-minimal
title: Stuart Woodward's Homepage
description: |
  A homepage for new browser tabs. Links to often used sites and quick access to information.
  <h2>Weather</h2>
  <a href="https://typhoon.yahoo.co.jp/weather/jp/typhoon/">Yahoo Japan Typhoon</a>
  <h2>Programming</h2>
  <iframe style="border: 0; width: 100%; height: 450px;" allowfullscreen frameborder="0" src="https://raindrop.io/stuartcw/programming-languages-31821983/embed"></iframe>
