#theme: jekyll-theme-minimal
title: Stuart Woodward's Homepage

# Remove any reference to a gem-based theme
theme: null

# Specify where your layout files are located
include:
  - _layouts
  - _includes
  - _sass
#  - assets

# Author settings
author:
  name: Stuart Woodward 
  email: stuart at stuartwoodward dot com 

# URL settings (if hosting on GitHub Pages)
url: "https://stuartcw.github.io/homepage/"
baseurl: "" # Leave empty unless your site is hosted in a subdirectory

# Markdown settings
markdown: kramdown
#highlighter: none
kramdown:
  input: GFM

# Exclude files or directories from the build
exclude:
  - README.md

# Plugins (add if you are using Jekyll plugins)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

description: |
  This is Stuart Woodward's browser homepage which is opened whenever he opens a new browser tab. It is configured in the browser to do so.

