theme: jekyll-theme-minimal
title: Stuart Woodward's Homepage
description: |
  A homepage for new browser tabs. Links to often used sites and quick access to information.
  ## Weather
  * [Yahoo Japan Typhoon](https://typhoon.yahoo.co.jp/weather/jp/typhoon/)

